site_name: Guía de Next.js
theme:
  name: material

nav:
  - Inicio: index.md
  - Guía:
      - Instalación: guia/instalacion.md
      - Uso: guia/uso.md
      - Optimización: guia/optimizacion.md
  - Acerca: about.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
